language: python
python:
  - 2.7
  - 3.3
  - 3.6
before_install:
  - pip install --upgrade pip setuptools wheel
  - pip install --only-binary=all coveralls
script:
  - python setup.py test
  - python -m coverage run --source=./peds setup.py test
after_success:
  - coveralls
